<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/21 14:42:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => '106',
  'name' => 'doctrine',
)),);
